# Generated by Django 4.2 on 2023-04-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=500, null=True)),
                ("prenom", models.CharField(max_length=500, null=True)),
                ("adresse", models.CharField(max_length=500, null=True)),
                ("tel", models.CharField(max_length=500, null=True)),
                ("image", models.ImageField(upload_to="chemin/vers/dossier/images/")),
                ("description", models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
