# Generated by Django 4.2 on 2023-04-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application001", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="image",
            field=models.ImageField(upload_to="upload/images"),
        ),
    ]
